import * as fs from 'fs'
import * as path from 'path'
import { Log } from '@quatrain/log'

export class CodeGenerator {
   /**
    * Génère une application complète dans le dossier cible
    */
   public static generate(config: any, targetDir: string): void {
      const fullTargetDir = path.resolve(process.cwd(), targetDir)
      
      // Ensure base directories exist
      const dirs = ['src/models', 'src/api', 'data/migrations/default']
      for (const dir of dirs) {
         const d = path.resolve(fullTargetDir, dir)
         if (!fs.existsSync(d)) {
            fs.mkdirSync(d, { recursive: true })
         }
      }

      this.generatePackageJson(config, fullTargetDir)
      this.generateTsConfig(fullTargetDir)
      
      const generatedModels = this.generateModels(config, fullTargetDir)
      this.generateApiEndpoints(config, fullTargetDir, generatedModels)
      this.generateIndex(config, fullTargetDir, generatedModels)
      this.generateMigration(config, fullTargetDir)

      Log.info(`[CodeGenerator] Application générée avec succès dans ${fullTargetDir}`)
   }

   private static generatePackageJson(config: any, targetDir: string): void {
      const packagePath = path.resolve(targetDir, 'package.json')
      
      const targetNpmTag = 'latest-dev' // Use 'latest' for production, 'latest-dev' for testing features

      const packageJson = {
         name: config.name?.toLowerCase().replace(/[^a-z0-9]/g, '-') || "quatrain-generated-app",
         version: "1.0.0",
         description: "Generated by Quatrain Studio",
         main: "src/index.ts",
         type: "module",
         scripts: {
            start: "bun run src/index.ts"
         },
         dependencies: {
            "@quatrain/core": targetNpmTag,
            "@quatrain/backend": targetNpmTag,
            "@quatrain/backend-sqlite": targetNpmTag,
            "@quatrain/api": targetNpmTag,
            "@quatrain/api-server": targetNpmTag,
            "@quatrain/backend-migrations": targetNpmTag
         } as Record<string, string>
      }

      if (config.authMode === 'oauth') {
         packageJson.dependencies['@quatrain/auth-oidc'] = targetNpmTag
      }
      
      if (config.backend?.adapter === 'PostgresAdapter') {
         packageJson.dependencies['@quatrain/backend-postgres'] = targetNpmTag
      }

      Log.info(`[CodeGenerator] Generating package.json with dependencies`)
      fs.writeFileSync(packagePath, JSON.stringify(packageJson, null, 2))
   }

   private static generateTsConfig(targetDir: string): void {
      const tsconfig = {
         compilerOptions: {
            target: "ES2022",
            module: "ESNext",
            moduleResolution: "node",
            esModuleInterop: true,
            strict: true,
            skipLibCheck: true,
            forceConsistentCasingInFileNames: true,
            outDir: "dist"
         },
         include: ["src/**/*", "data/migrations/**/*"]
      }
      fs.writeFileSync(path.resolve(targetDir, 'tsconfig.json'), JSON.stringify(tsconfig, null, 2))
   }

   private static generateModels(config: any, targetDir: string): string[] {
      const models = config.models || []
      const generatedNames: string[] = []

      for (const model of models) {
         if (!model.name) continue
         const className = model.name
         const collectionName = model.collectionName || className.toLowerCase()
         generatedNames.push(className)

         // Use imports from core properties
         const propsCode = model.properties.map((p: any) => {
            const propType = p.type // e.g. "StringProperty"
            return `   {
      name: '${p.name}',
      type: ${propType}.TYPE,
      mandatory: ${p.options?.mandatory ? 'true' : 'false'}
   }`
         }).join(',\n')

         const propTypesToImport = Array.from(new Set(model.properties.map((p: any) => p.type)))
         
         const modelCode = `import { PersistedBaseObject } from '@quatrain/backend'
import { ${propTypesToImport.join(', ')} } from '@quatrain/core'

export const ${className}Properties = [
${propsCode}
]

export class ${className} extends PersistedBaseObject {
   static PROPS_DEFINITION = ${className}Properties
   static COLLECTION = '${collectionName}'

   static async factory(src: any = undefined): Promise<${className}> {
      return super.factory(src, ${className})
   }
}
`
         fs.writeFileSync(path.resolve(targetDir, `src/models/${className}.ts`), modelCode)
      }

      return generatedNames
   }

   private static generateApiEndpoints(config: any, targetDir: string, models: string[]): void {
      for (const className of models) {
         const apiCode = `import { CrudEndpoint } from '@quatrain/api-server'
import { ${className} } from '../models/${className}'

export class ${className}Api extends CrudEndpoint {
   constructor() {
      super('/api/${className.toLowerCase()}s', ${className})
   }
}
`
         fs.writeFileSync(path.resolve(targetDir, `src/api/${className}Api.ts`), apiCode)
      }
   }

   private static generateIndex(config: any, targetDir: string, models: string[]): void {
      const adapterClass = config.backend?.adapter === 'PostgresAdapter' ? 'PostgresAdapter' : 'SQLiteAdapter'
      const adapterImport = config.backend?.adapter === 'PostgresAdapter' ? '@quatrain/backend-postgres' : '@quatrain/backend-sqlite'
      
      const modelImports = models.map(m => `import { ${m} } from './models/${m}'`).join('\n')
      const apiImports = models.map(m => `import { ${m}Api } from './api/${m}Api'`).join('\n')
      const apiRegisters = models.map(m => `      server.addEndpoint(new ${m}Api())`).join('\n')

      const indexCode = `import * as path from 'path'
import { Backend, InjectMetaMiddleware } from '@quatrain/backend'
import { ${adapterClass} } from '${adapterImport}'
import { ExpressAdapter } from '@quatrain/api-server'
import { MigrationManager } from '@quatrain/backend-migrations'
${config.authMode === 'oauth' ? `import { AuthOIDC } from '@quatrain/auth-oidc'\n` : ''}
${modelImports}
${apiImports}

;(async () => {
   try {
      const adapter = new ${adapterClass}({ 
         config: ${adapterClass === 'SQLiteAdapter' ? '{ database: path.resolve(process.cwd(), "data/app.sqlite") }' : 'process.env.DATABASE_URL'},
         middlewares: [new InjectMetaMiddleware()]
      })

      Backend.init(adapter)
      
      const mm = new MigrationManager()
      await mm.up()
      
      const server = new ExpressAdapter()
      
${apiRegisters}

${config.authMode === 'oauth' ? `      // Initialize OIDC Auth
      const oidc = AuthOIDC.init('http://localhost:4001')
      server.getApp().use('/oidc', oidc.callback())
` : ''}

      const PORT = Number(process.env.PORT) || 4001
      server.start(PORT, () => {
         console.log(\`🚀 Server started on port \${PORT}\`)
      })
   } catch (e) {
      console.error(e)
      process.exit(1)
   }
})()
`
      fs.writeFileSync(path.resolve(targetDir, 'src/index.ts'), indexCode)
   }

   private static generateMigration(config: any, targetDir: string): void {
      const models = config.models || []
      
      let upQueries = ''
      let downQueries = ''

      for (const model of models) {
         if (!model.name) continue
         const collectionName = model.collectionName || model.name.toLowerCase()
         
         const columns = model.properties.map((p: any) => {
            // Very simplified SQLite type mapping for the PoC
            let sqlType = 'TEXT'
            if (p.type === 'NumberProperty' || p.type === 'BooleanProperty') sqlType = 'INTEGER'
            return `${p.name} ${sqlType}`
         }).join(',\n         ')

         upQueries += `
      await adapter.rawQuery(\`CREATE TABLE IF NOT EXISTS ${collectionName} (
         id TEXT PRIMARY KEY,
         status TEXT,
         created_at TEXT,
         updated_at TEXT,
         created_by TEXT,
         updated_by TEXT,
         ${columns}
      )\`)\n`

         downQueries += `
      await adapter.rawQuery('DROP TABLE IF EXISTS ${collectionName}')\n`
      }

      const migrationCode = `import { AbstractBackendAdapter } from '@quatrain/backend'

export const up = async ({ context: adapter }: { context: AbstractBackendAdapter }) => {
   try {${upQueries}
   } catch (e) {
      console.error('Migration up error', e)
   }
}

export const down = async ({ context: adapter }: { context: AbstractBackendAdapter }) => {
   try {${downQueries}
   } catch (e) {
      console.error('Migration down error', e)
   }
}
`
      const timestamp = new Date().toISOString().replace(/[-:T]/g, '').slice(0, 14)
      fs.writeFileSync(path.resolve(targetDir, `data/migrations/default/${timestamp}_init.ts`), migrationCode)
   }
}
