services:
  engine:
    build:
      context: .
      dockerfile: Containerfile
    container_name: quatrain-app-engine
    restart: unless-stopped
    ports:
      - 4001:4001
    environment:
      NODE_ENV: production
    volumes:
      - ./quatrain.json:/app/quatrain.json:ro
      - ./data:/app/data
  ui:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: quatrain-app-ui
    restart: unless-stopped
    ports:
      - 3000:80
    depends_on:
      - engine
