FROM oven/bun:latest
WORKDIR /app
# Pour le PoC, on installe un serveur HTTP minimal pour l'instant
RUN bun init -y
RUN bun add serve
COPY quatrain.json /app/quatrain.json
EXPOSE 3000 4000
CMD ["bun", "x", "serve", "-p", "3000", "."]