import * as statuses from './statuses'

describe('Core Statuses', () => {
   it('should export all expected standard and complementary statuses as correct strings', () => {
      expect(statuses.ACTIVE).toBe('active')
      expect(statuses.APPROVED).toBe('approved')
      expect(statuses.ARCHIVED).toBe('archived')
      expect(statuses.BLOCKED).toBe('blocked')
      expect(statuses.CANCELLED).toBe('cancelled')
      expect(statuses.COMPLETED).toBe('completed')
      expect(statuses.CONVERTING).toBe('converting')
      expect(statuses.CREATED).toBe('created')
      expect(statuses.DELETABLE).toBe('deletable')
      expect(statuses.DELETED).toBe('deleted')
      expect(statuses.DISABLED).toBe('disabled')
      expect(statuses.DONE).toBe('done')
      expect(statuses.DRAFT).toBe('draft')
      expect(statuses.DOWNLOADING).toBe('downloading')
      expect(statuses.DOWNLOADED).toBe('downloaded')
      expect(statuses.DOWNLOAD_KO).toBe('download_ko')
      expect(statuses.ERROR).toBe('error')
      expect(statuses.EXPIRED).toBe('expired')
      expect(statuses.FAILED).toBe('failed')
      expect(statuses.GENERATING).toBe('generating')
      expect(statuses.GENERATED).toBe('generated')
      expect(statuses.IN_PROGRESS).toBe('in_progress')
      expect(statuses.KO).toBe('ko')
      expect(statuses.OK).toBe('ok')
      expect(statuses.PAUSED).toBe('paused')
      expect(statuses.PENDING).toBe('pending')
      expect(statuses.PREPARING).toBe('preparing')
      expect(statuses.PROCESSING).toBe('processing')
      expect(statuses.PUBLISHED).toBe('published')
      expect(statuses.QUEUED).toBe('queued')
      expect(statuses.REJECTED).toBe('rejected')
      expect(statuses.RUNNING).toBe('running')
      expect(statuses.SUCCESS).toBe('success')
      expect(statuses.SUSPENDED).toBe('suspended')
      expect(statuses.UNKNOWN).toBe('unknown')
      expect(statuses.UPDATED).toBe('updated')
      expect(statuses.UPLOADING).toBe('uploading')
      expect(statuses.UPLOADED).toBe('uploaded')
      expect(statuses.UPLOAD_KO).toBe('upload_ko')
      expect(statuses.VALIDATED).toBe('validated')
      expect(statuses.ZIPPING).toBe('zipping')
   })

   it('should support grouped DOWNLOAD and UPLOAD status namespaces with backward-compatible values', () => {
      expect(statuses.DOWNLOAD.STARTED).toBe('downloading')
      expect(statuses.DOWNLOAD.FINISHED).toBe('downloaded')
      expect(statuses.DOWNLOAD.OK).toBe('downloaded')
      expect(statuses.DOWNLOAD.KO).toBe('download_ko')

      expect(statuses.UPLOAD.STARTED).toBe('uploading')
      expect(statuses.UPLOAD.FINISHED).toBe('uploaded')
      expect(statuses.UPLOAD.OK).toBe('uploaded')
      expect(statuses.UPLOAD.KO).toBe('upload_ko')
   })

   it('should support grouped DOCUMENT status namespace with expected lifecycle values', () => {
      expect(statuses.DOCUMENT.DRAFT).toBe('draft')
      expect(statuses.DOCUMENT.PENDING).toBe('pending')
      expect(statuses.DOCUMENT.APPROVED).toBe('approved')
      expect(statuses.DOCUMENT.REJECTED).toBe('rejected')
      expect(statuses.DOCUMENT.PUBLISHED).toBe('published')
      expect(statuses.DOCUMENT.ARCHIVED).toBe('archived')
   })
})


